version: '3.8'

services:
  web_service:
    build: .
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db_service

  db_service:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=p8_db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/letsencrypt:/var/www/certbot
    depends_on:
      - web_service
    logging:
        options:
            max-size: "10m"
            max-file: "3"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/letsencrypt:/var/www/certbot:ro
    command: certonly --webroot -w /var/www/certbot --redirect --force-renewal --email khasanjon@gmail.com -d xolmomin.diordev.me --agree-tos

volumes:
  postgres_data:
  static_volume:
  media_volume: