# Generated by Django 4.2.2 on 2023-06-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_parameter_paramvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adverts/')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.advert')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=55)),
                ('type', models.CharField(max_length=255)),
                ('value', models.JSONField(default=dict)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.advert')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=55)),
                ('range', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('enum', 'Enum'), ('bool', 'Bool'), ('digit', 'Digit'), ('salary', 'Salary'), ('hidden', 'Hidden')], max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('category_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.categoryparam')),
            ],
        ),
        migrations.RemoveField(
            model_name='paramvalue',
            name='parameter',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='ParamValue',
        ),
    ]
